export default function Marquee() {
  return (
    <div
      className="marquee"
      aria-label="Django, FastAPI, Python, Kotlin, Java, Android, Firebase, JavaScript"
    >
      <div className="marquee-track" aria-hidden="true">
        <span>Django</span>
        <i>✦</i>
        <span>FastAPI</span>
        <i>✦</i>
        <span>Python</span>
        <i>✦</i>
        <span>Kotlin</span>
        <i>✦</i>
        <span>Java</span>
        <i>✦</i>
        <span>Android</span>
        <i>✦</i>
        <span>Firebase</span>
        <i>✦</i>
        <span>JavaScript</span>
        <i>✦</i>
        <span>Django</span>
        <i>✦</i>
        <span>FastAPI</span>
        <i>✦</i>
        <span>Python</span>
        <i>✦</i>
        <span>Kotlin</span>
        <i>✦</i>
        <span>Java</span>
        <i>✦</i>
        <span>Android</span>
        <i>✦</i>
        <span>Firebase</span>
        <i>✦</i>
        <span>JavaScript</span>
        <i>✦</i>
        <span>Django</span>
        <i>✦</i>
        <span>FastAPI</span>
        <i>✦</i>
        <span>Python</span>
        <i>✦</i>
        <span>Kotlin</span>
        <i>✦</i>
        <span>Java</span>
        <i>✦</i>
        <span>Android</span>
        <i>✦</i>
        <span>Firebase</span>
        <i>✦</i>
        <span>JavaScript</span>
        <i>✦</i>
      </div>
    </div>
  );
}
